// <auto-generated />
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Ignored", Scope = "namespace", Target = "~N:Collections.Specialized")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1000:Keywords should be spaced correctly", Justification = "VSCode always removes the space", Scope = "member", Target = "~F:Collections.Specialized.DigitPrefixLookup`1.root")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1000:Keywords should be spaced correctly", Justification = "VSCode always removes the space", Scope = "member", Target = "~M:Collections.Specialized.DigitPrefixLookup`1.GetEnumerator~System.Collections.Generic.IEnumerator{System.Collections.Generic.KeyValuePair{System.String,`0}}")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "VSCode always removes the space", Scope = "member", Target = "~M:Collections.Specialized.DigitPrefixLookup`1.TryAdd(System.String,`0)~System.Boolean")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "VSCode always removes the space", Scope = "member", Target = "~M:Collections.Specialized.DigitPrefixLookup`1.TryGetValue(System.String,`0@)~System.Boolean")]
